## 服务器
server:
  port: 80
  servlet:
    context-path:

## 修改Thymeleaf缓存为false
spring:
  thymeleaf:
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12897777
    hikari:
      maximum-pool-size: 20

# 整合MyBatis
mybatis:
  type-aliases-package: com.qdu.bean
  mapper-locations: classpath:/mappers/*.xml

## PageHelper分页插件
pagehelper:
  reasonable: true

logging:
  level:
    com.etoak.mapper: debug